/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "alpslib"
include(":alpslib-npc")
include(":alpslib-hologram")
include(":alpslib-utils")
include(":alpslib-libpsterra")
include(":alpslib-io")
include(":alpslib-geo")
project(":alpslib-npc").projectDir = file("npc")
project(":alpslib-hologram").projectDir = file("hologram")
project(":alpslib-utils").projectDir = file("utils")
project(":alpslib-libpsterra").projectDir = file("libpsterra")
project(":alpslib-io").projectDir = file("io")
project(":alpslib-geo").projectDir = file("geo")