/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    alias(libs.plugins.gradleup.shadow)
}

dependencies {
    api(libs.com.github.cryptomorin.xseries)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.arcaniax.headdatabase.api)
}

description = "AlpsLib-Utils"
version = "1.3.7"

publishing {
    publications {
        create<MavenPublication>("shadow") {
            from(components["shadow"])
        }
    }
}

tasks.shadowJar {
    exclude("org/slf4j/**")
    exclude("org/jetbrains/annotations/**")
    archiveClassifier = ""
}

tasks.assemble {
    dependsOn(tasks.shadowJar) // Ensure that the shadowJar task runs before the build task
}

tasks.jar {
    enabled = false // Disable the default jar task since we are using shadowJar
}