/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.github.cryptomorin.xseries)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.arcaniax.headdatabase.api)
}

description = "AlpsLib-Utils"
version = "1.3.8"
